# Generated by Django 5.1.3 on 2024-12-02 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_options_alter_client_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientconnections',
            name='invited_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter_client', to='clients.client', unique=True),
        ),
    ]
