# Generated by Django 5.1.3 on 2024-12-02 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_client_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='user_id',
            new_name='user',
        ),
    ]
